#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -option "grp:win_space_toggle" us,ru &

xsetroot -cursor_name left_ptr

# Multiple monitor support
sh $HOME/.config/bspwm/dual_monitors.sh

# Window borders (Auto-Generate)
bspc config focus_follows_pointer true
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# start resources
xrdb merge ~/.Xresources

# Random Wallpaper Script
feh --bg-fill /home/saniqp/Pictures/arch.png

# Run polybar
polybar &

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
# start compositor
picom  &

# == autostart ==
pkill flameshot; flameshot &

# run cursor tracker
pkill cursor_tracker ; ~/bin/cursor_tracker.sh
